name: Notes build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m venv mkdocs-venv
          source mkdocs-venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Build MkDocs site
        run: |
          source mkdocs-venv/bin/activate
          mkdocs build
          zip -r documentation.zip site

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: |
            site
            documentation.zip
            documentation.pdf

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: site
          path: public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
